name       : sshfs-fuse
version    : 2.9
release    : 3
source     :
    - https://github.com/libfuse/sshfs/releases/download/sshfs-2.9/sshfs-2.9.tar.gz : 46d1e1287ce97255fcb50010355184d8c5585329f73ab1e755217419a8e6e5de
license    : GPL-2.0
component  : network.util
summary    : SSH Filesystem
description: |
    SSH Filesystem
builddeps  :
    - pkgconfig(fuse)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
