name       : sshfs-fuse
version    : '2.10'
release    : 4
source     :
    - https://github.com/libfuse/sshfs/releases/download/sshfs-2.10/sshfs-2.10.tar.gz : 70845dde2d70606aa207db5edfe878e266f9c193f1956dd10ba1b7e9a3c8d101
license    : GPL-2.0
component  : network.util
summary    : A network filesystem client to connect to SSH servers
description: |
    SSHFS allows you to mount a remote filesystem using SFTP.
    Most SSH servers support and enable this SFTP access by default,
    so SSHFS is very simple to use - there's nothing to do on the server-side.
builddeps  :
    - pkgconfig(fuse)
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
