name       : sshfs-fuse
version    : 2.8
release    : 2
source     :
    - https://github.com/libfuse/sshfs/releases/download/sshfs_2.8/sshfs-2.8.tar.gz : 7f689174d02e6b7e2631306fda4fb8e6b4483102d1bce82b3cdafba33369ad22
license    : GPL-2.0
component  : network.util
summary    : SSH Filesystem
description: |
    SSH Filesystem
builddeps  :
    - pkgconfig(fuse)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
