name       : sshfs-fuse
version    : 3.7.1
release    : 8
source     :
    - https://github.com/libfuse/sshfs/archive/refs/tags/sshfs-3.7.1.tar.gz : 0f0f8f239555effd675d03a3cabfb35ef691a3054c98b62bc28e85620ad9e30d
license    : GPL-2.0-only
component  : network.util
summary    : A network filesystem client to connect to SSH servers
description: |
    SSHFS allows you to mount a remote filesystem using SFTP. Most SSH servers support and enable this SFTP access by default, so SSHFS is very simple to use - there's nothing to do on the server-side.
builddeps  :
    - pkgconfig(fuse3)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
